name: Multi-distro Package Build

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    branches:
      - devel
  workflow_dispatch:

env:
  REPO: ${{ github.repository }}
  REF: ${{ github.ref }}
  REVISION: ${{ github.run_number }}
  AUTHOR: ${{ secrets.RELEASE_USERNAME }}
  PAT: ${{ secrets.RELEASE_TOKEN }}
  QUEUE: Ananda-Aropa/aaropa_debian_queue

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Enqueue
        if: always()
        env:
          REPO: ${{ env.REPO }}
          GITHUB_USER: ${{ env.AUTHOR }}
          GITHUB_TOKEN: ${{ env.PAT }}
          QUEUE: ${{ env.QUEUE }}
          REF: ${{ env.REF }}
        run: |
          BRANCH=${REF##*/}
          git clone -b $BRANCH https://github.com/$QUEUE queue
          cd queue
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url --push origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/$QUEUE
          touch ${REPO##*/} &&
          git add ${REPO##*/} &&
          git commit -m "Enqueue ${REPO}" &&
          git push origin $BRANCH || true
          cd ..
          rm -rf queue

      - name: Check out
        uses: actions/checkout@v6

      - name: Set up source files
        run: |
          bash ./distro/debian/setup.sh
          bash ./distro/rpm/setup.sh
          bash ./distro/arch/gen_pkgbuild.sh
          bash ./distro/alpine/setup.sh
          cp -r -t . distro/{debian,rpm}


      - name: Build DEB package
        uses: Ananda-Aropa/build-deb@main
        with:
          distro: debian:unstable-slim
          arch: amd64
          docker_arch_specific: true

      - name: Extract Debian artifact
        run: unzip -o built-deb-files.zip

      - name: Build Arch package
        run: |
          docker buildx build -f ci/docker/archlinux.dockerfile -t arch-build --allow security.insecure --output type=tar,dest=arch-install.tar .
          mkdir arch-install
          sudo tar -C arch-install -psxf arch-install.tar output
          sudo find arch-install/output -mindepth 1 -maxdepth 1 -name "*.pkg.tar*" -exec mv {} ./ \;
          sudo rm -rf arch-install arch-install.tar

      - name: Build Alpine package
        run: |
          docker buildx build -f ci/docker/alpine.dockerfile -t alpine-build --allow security.insecure --output type=tar,dest=alpine-install.tar .
          mkdir alpine-install
          sudo tar -C alpine-install -psxf alpine-install.tar output
          sudo find alpine-install/output -mindepth 1 -maxdepth 1 -name "*.apk" -exec mv {} ./ \;
          sudo rm -rf alpine-install alpine-install.tar

      - name: Build RPM package
        run: |
          docker buildx build -f ci/docker/rpm.dockerfile -t rpm-build --allow security.insecure --output type=tar,dest=rpm-install.tar .
          mkdir rpm-install
          sudo tar -C rpm-install -psxf rpm-install.tar output
          sudo find rpm-install/output -mindepth 1 -maxdepth 1 -name "*.rpm" -exec mv {} ./ \;
          sudo rm -rf rpm-install rpm-install.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          path: |
            metadata.yml
            *_*_*.buildinfo
            *_*_*.changes
            *_*_*.deb
            *_*_*.udeb
            *.pkg.tar*
            *.apk
            *.rpm

      - name: Dequeue
        if: always()
        env:
          REPO: ${{ env.REPO }}
          GITHUB_USER: ${{ env.AUTHOR }}
          GITHUB_TOKEN: ${{ env.PAT }}
          QUEUE: ${{ env.QUEUE }}
          REF: ${{ env.REF }}
        run: |
          BRANCH=${REF##*/}
          git clone -b $BRANCH https://github.com/$QUEUE queue
          cd queue
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url --push origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/$QUEUE
          rm -rf ${REPO##*/}
          git add .
          git commit -m "Dequeue ${REPO}"
          while ! git push origin $BRANCH; do sleep 5; git fetch --no-tags origin $BRANCH; git rebase origin/$BRANCH; done
          cd ..
          rm -rf queue

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup variables
        run: |
          echo "VERSION=$(cat VERSION | cut -d'v' -f2)" >>"$GITHUB_ENV"
          echo "DATE=$(date -u +'%Y%m%d')" >>"$GITHUB_ENV"

      - name: Download artifacts
        id: download-artifacts
        uses: actions/download-artifact@v8
        with:
          path: out
          pattern: "*"
          merge-multiple: true

      - name: List Files
        run: ls -R ${{ steps.download-artifacts.outputs.download-path }}

      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          tag_name: "${{ env.VERSION }}-${{ env.REVISION }}"
          name: "Release ${{ env.VERSION }}-${{ env.REVISION }}-${{ env.DATE }}"
          files: |
            ${{ steps.download-artifacts.outputs.download-path }}/*
