name: Generate linux packages

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build DEB package
        uses: DevChall-by-SDCY-and-VXM/debian-buildpackage-template@main
        with:
          distro: devuan/migrated:ceres-slim
          package_maintainer: Shadichy <shadichy@blisslabs.org>

      - name: Extract artifact
        run: unzip -o built-deb-files.zip

      - name: Build Arch pacakge
        run: |
          # Build docker image
          docker buildx create --use --name archlinux-devel --buildkitd-flags '--allow-insecure-entitlement security.insecure'
          docker buildx build --builder archlinux-devel -f archlinux.dockerfile -t archlinux --allow security.insecure --output type=tar,dest=install.tar .

          # Export it to install
          mkdir install
          sudo tar -C install -psxf install.tar

          # Move content out
          mv install/*.pkg.tar* ./

          # Clean up
          sudo rm -rf install install.tar

      - name: Set Vars
        id: vars
        run: |
          echo "arch=$(dpkg --print-architecture)" >>"$GITHUB_OUTPUT"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            metadata.yml
            metadata.yml
            *_*_*.buildinfo
            *_*_*.changes
            *_*_*.deb
            *_*_*.udeb
            *.pkg.tar*

  release:
    name: Release
    needs: build
    if: ((github.event_name == 'push' || github.event_name == 'workflow_dispatch') && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Download buildfiles
        id: download-buildfiles
        uses: actions/download-artifact@v4
        with:
          path: out
          pattern: "*"
          merge-multiple: true

      - name: List Files
        run: ls -R ${{ steps.download-buildfiles.outputs.download-path }}

      - uses: "softprops/action-gh-release@v2.1.0"
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            ${{ steps.download-buildfiles.outputs.download-path }}/*
